source 'https://github.com/CocoaPods/Specs.git'

target 'InstagramAssetsPicker', :exclusive => true do
  pod "InstagramAssetsPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "InstagramAssetsPicker", :path => "../"

  
end
